cacheFolder: ./.yarn/cache

cloneConcurrency: 8

enableColors: true

enableHyperlinks: true

enableProgressBars: true

enableTimers: true

httpRetry: 4

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-4.0.0-rc.29.cjs
